In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.naive_bayes import BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
df=pd.read_csv("C:/Users/cherr/Documents/btech certificates/resume/hhh.csv" ,encoding="latin-1")

In [3]:
df.head()


class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df.head(n=10)

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   
5  spam  FreeMsg Hey there darling it's been 3 week's n...        NaN   
6   ham  Even my brother is not like to speak with me. ...        NaN   
7   ham  As per your request 'Melle Melle (Oru Minnamin...        NaN   
8  spam  WINNER!! As a valued network customer you have...        NaN   
9  spam  Had your mobile 11 months or more? U R entitle...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN  
5        NaN        NaN  
6        NaN        NaN  
7        NaN        NaN  
8        NaN        NaN  
9        NaN        NaN

In [5]:
df.shape

(5572, 5)

In [6]:
np.unique(df['class'])

array(['ham', 'spam'], dtype=object)

In [7]:
np.unique(df['message'])

array([' &lt;#&gt;  in mca. But not conform.',
       ' &lt;#&gt;  mins but i had to stop somewhere first.',
       ' &lt;DECIMAL&gt; m but its not a common car here so its better to buy from china or asia. Or if i find it less expensive. I.ll holla',
       ..., 'ÌÏ thk of wat to eat tonight.', 'ÌÏ v ma fan...',
       'ÌÏ wait 4 me in sch i finish ard 5..'], dtype=object)

In [8]:
x=df['message'].values
y=df['class'].values
cv=CountVectorizer()
x=cv.fit_transform(x)
v=x.toarray()
print(v)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
first_col=df.pop('message')
df.insert(0,'message',first_col)
df


message class Unnamed: 2  \
0     Go until jurong point, crazy.. Available only ...   ham        NaN   
1                         Ok lar... Joking wif u oni...   ham        NaN   
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam        NaN   
3     U dun say so early hor... U c already then say...   ham        NaN   
4     Nah I don't think he goes to usf, he lives aro...   ham        NaN   
...                                                 ...   ...        ...   
5567  This is the 2nd time we have tried 2 contact u...  spam        NaN   
5568              Will Ì_ b going to esplanade fr home?   ham        NaN   
5569  Pity, * was in mood for that. So...any other s...   ham        NaN   
5570  The guy did some bitching but I acted like i'd...   ham        NaN   
5571                         Rofl. Its true to its name   ham        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [10]:
trainx=x[:4180]
trainy=y[:4180]
testx=x[4180:]
testy=y[4180:]


In [11]:
bnb=BernoulliNB(binarize=0.0)
model=bnb.fit(trainx,trainy)
ypredtrain=bnb.predict(trainx)
ypredtest=bnb.predict(testx)

In [12]:
print(bnb.score(trainx,trainy)*100)
print(bnb.score(testx,testy)*100)

98.70813397129187
98.20402298850574


In [13]:
from sklearn.metrics import classification_report
print(classification_report(trainy,ypredtrain))


              precision    recall  f1-score   support

         ham       0.99      1.00      0.99      3615
        spam       0.99      0.91      0.95       565

    accuracy                           0.99      4180
   macro avg       0.99      0.95      0.97      4180
weighted avg       0.99      0.99      0.99      4180



In [14]:
from sklearn.metrics import classification_report
print(classification_report(testy,ypredtest))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1210
        spam       0.99      0.87      0.93       182

    accuracy                           0.98      1392
   macro avg       0.99      0.93      0.96      1392
weighted avg       0.98      0.98      0.98      1392



In [15]:
import numpy as np
import pandas as pd

In [16]:
df=pd.read_csv('C:/Users/cherr/Documents/btech certificates/resume/hhh.csv',encoding="latin-1")
df.head()

class                                            message Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [17]:
df.describe()

class                 message  \
count   5572                    5572   
unique     2                    5169   
top      ham  Sorry, I'll call later   
freq    4825                      30   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2

In [18]:
df=pd.read_csv('C:/Users/cherr/Documents/btech certificates/resume/stress.csv')
df.head()

subreddit post_id sentence_range  \
0              ptsd  8601tu       (15, 20)   
1        assistance  8lbrx9         (0, 5)   
2              ptsd  9ch1zh       (15, 20)   
3     relationships  7rorpp        [5, 10]   
4  survivorsofabuse  9p2gbc         [0, 5]   

                                                text     id  label  \
0  He said he had not felt that way before, sugge...  33181      1   
1  Hey there r/assistance, Not sure if this is th...   2606      0   
2  My mom then hit me with the newspaper and it s...  38816      1   
3  until i met my new boyfriend, he is amazing, h...    239      1   
4  October is Domestic Violence Awareness Month a...   1421      1   

   confidence  social_timestamp  social_karma  syntax_ari  ...  \
0         0.8        1521614353             5    1.806818  ...   
1         1.0        1527009817             4    9.429737  ...   
2         0.8        1535935605             2    7.769821  ...   
3         0.6        1516429555             0    2.667798  ...   
4         0.8        1539809005            24    7.554238  ...   

   lex_dal_min_pleasantness  lex_dal_min_activation  lex_dal_min_imagery  \
0                     1.000                  1.1250                  1.0   
1                     1.125                  1.0000                  1.0   
2                     1.000                  1.1429                  1.0   
3                     1.000                  1.1250                  1.0   
4                     1.000                  1.1250                  1.0   

   lex_dal_avg_activation  lex_dal_avg_imagery  lex_dal_avg_pleasantness  \
0                 1.77000              1.52211                   1.89556   
1                 1.69586              1.62045                   1.88919   
2                 1.83088              1.58108                   1.85828   
3                 1.75356              1.52114                   1.98848   
4                 1.77644              1.64872                   1.81456   

   social_upvote_ratio  social_num_comments  syntax_fk_grade  sentiment  
0                 0.86                    1         3.253573  -0.002742  
1                 0.65                    2         8.828316   0.292857  
2                 0.67                    0         7.841667   0.011894  
3                 0.50                    5         4.104027   0.141671  
4                 1.00                    1         7.910952  -0.204167  

[5 rows x 116 columns]

In [19]:
df.describe()

id        label   confidence  social_timestamp  social_karma  \
count   2838.000000  2838.000000  2838.000000      2.838000e+03   2838.000000   
mean   13751.999295     0.524313     0.808972      1.518107e+09     18.262156   
std    17340.161897     0.499497     0.177038      1.552209e+07     79.419166   
min        4.000000     0.000000     0.428571      1.483274e+09      0.000000   
25%      926.250000     0.000000     0.600000      1.509698e+09      2.000000   
50%     1891.500000     1.000000     0.800000      1.517066e+09      5.000000   
75%    25473.750000     1.000000     1.000000      1.530898e+09     10.000000   
max    55757.000000     1.000000     1.000000      1.542592e+09   1435.000000   

        syntax_ari  lex_liwc_WC  lex_liwc_Analytic  lex_liwc_Clout  \
count  2838.000000  2838.000000        2838.000000     2838.000000   
mean      4.684272    85.996124          35.240941       40.948231   
std       3.316435    32.334887          26.486189       31.587117   
min      -6.620000     5.000000           1.000000        1.000000   
25%       2.464243    65.000000          12.410000       12.135000   
50%       4.321886    81.000000          29.420000       33.520000   
75%       6.505657   101.000000          55.057500       69.320000   
max      24.074231   310.000000          99.000000       99.000000   

       lex_liwc_Authentic  ...  lex_dal_min_pleasantness  \
count         2838.000000  ...               2838.000000   
mean            67.044249  ...                  1.088001   
std             32.880644  ...                  0.117159   
min              1.000000  ...                  1.000000   
25%             41.070000  ...                  1.000000   
50%             80.710000  ...                  1.000000   
75%             96.180000  ...                  1.142900   
max             99.000000  ...                  1.900000   

       lex_dal_min_activation  lex_dal_min_imagery  lex_dal_avg_activation  \
count             2838.000000          2838.000000             2838.000000   
mean                 1.120099             1.000211                1.722759   
std                  0.085227             0.006500                0.047835   
min                  1.000000             1.000000                1.485400   
25%                  1.000000             1.000000                1.691430   
50%                  1.142900             1.000000                1.721430   
75%                  1.142900             1.000000                1.751760   
max                  1.500000             1.200000                2.007400   

       lex_dal_avg_imagery  lex_dal_avg_pleasantness  social_upvote_ratio  \
count          2838.000000               2838.000000          2838.000000   
mean              1.536400                  1.879385             0.843517   
std               0.102971                  0.058932             0.174794   
min               1.200000                  1.561150             0.140000   
25%               1.469745                  1.841782             0.750000   
50%               1.530295                  1.878250             0.890000   
75%               1.596030                  1.916243             1.000000   
max               2.066670                  2.158490             1.000000   

       social_num_comments  syntax_fk_grade    sentiment  
count          2838.000000      2838.000000  2838.000000  
mean              9.948555         5.448836     0.040740  
std              21.798032         2.535829     0.195490  
min               0.000000        -1.918000    -1.000000  
25%               2.000000         3.729973    -0.072222  
50%               5.000000         5.210000     0.044821  
75%              10.000000         6.855217     0.166667  
max             416.000000        21.198919     1.000000  

[8 rows x 112 columns]

In [20]:
df.isnull()

subreddit  post_id  sentence_range   text     id  label  confidence  \
0         False    False           False  False  False  False       False   
1         False    False           False  False  False  False       False   
2         False    False           False  False  False  False       False   
3         False    False           False  False  False  False       False   
4         False    False           False  False  False  False       False   
...         ...      ...             ...    ...    ...    ...         ...   
2833      False    False           False  False  False  False       False   
2834      False    False           False  False  False  False       False   
2835      False    False           False  False  False  False       False   
2836      False    False           False  False  False  False       False   
2837      False    False           False  False  False  False       False   

      social_timestamp  social_karma  syntax_ari  ...  \
0                False         False       False  ...   
1                False         False       False  ...   
2                False         False       False  ...   
3                False         False       False  ...   
4                False         False       False  ...   
...                ...           ...         ...  ...   
2833             False         False       False  ...   
2834             False         False       False  ...   
2835             False         False       False  ...   
2836             False         False       False  ...   
2837             False         False       False  ...   

      lex_dal_min_pleasantness  lex_dal_min_activation  lex_dal_min_imagery  \
0                        False                   False                False   
1                        False                   False                False   
2                        False                   False                False   
3                        False                   False                False   
4                        False                   False                False   
...                        ...                     ...                  ...   
2833                     False                   False                False   
2834                     False                   False                False   
2835                     False                   False                False   
2836                     False                   False                False   
2837                     False                   False                False   

      lex_dal_avg_activation  lex_dal_avg_imagery  lex_dal_avg_pleasantness  \
0                      False                False                     False   
1                      False                False                     False   
2                      False                False                     False   
3                      False                False                     False   
4                      False                False                     False   
...                      ...                  ...                       ...   
2833                   False                False                     False   
2834                   False                False                     False   
2835                   False                False                     False   
2836                   False                False                     False   
2837                   False                False                     False   

      social_upvote_ratio  social_num_comments  syntax_fk_grade  sentiment  
0                   False                False            False      False  
1                   False                False            False      False  
2                   False                False            False      False  
3                   False                False            False      False  
4                   False                False            False      False  
...                   ...           

In [21]:
df.isnull().sum()

subreddit                   0
post_id                     0
sentence_range              0
text                        0
id                          0
                           ..
lex_dal_avg_pleasantness    0
social_upvote_ratio         0
social_num_comments         0
syntax_fk_grade             0
sentiment                   0
Length: 116, dtype: int64

In [22]:
import nltk
import re
from nltk. corpus import stopwords
import string
nltk. download( 'stopwords' )
stemmer = nltk. SnowballStemmer("english")
stopword=set (stopwords . words ( 'english' ))


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\cherr\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [24]:

def clean(text):
    text = str(text) . lower()  #returns a string where all characters are lower case. Symbols and Numbers are ignored.
    text = re. sub('\[.*?\]',' ',text)  #substring and returns a string with replaced values.
    text = re. sub('https?://\S+/www\. \S+', ' ', text)#whitespace char with pattern
    text = re. sub('<. *?>+', ' ', text)#special char enclosed in square brackets
    text = re. sub(' [%s]' % re. escape(string. punctuation), ' ', text)#eliminate punctuation from string
    text = re. sub(' \n',' ', text)
    text = re. sub(' \w*\d\w*' ,' ', text)#word character ASCII punctuation
    text = [word for word in text. split(' ') if word not in stopword]  #removing stopwords
    text =" ". join(text)
    text = [stemmer . stem(word) for word in text. split(' ') ]#remove morphological affixes from words
    text = " ". join(text)
    return text
df [ "text"] = df["text"]. apply(clean)


In [25]:
from sklearn. feature_extraction. text import CountVectorizer
from sklearn. model_selection import train_test_split

x = np.array (df["text"])
y = np.array (df["label"])

cv = CountVectorizer ()
X = cv. fit_transform(x)
print(X)
xtrain, xtest, ytrain, ytest = train_test_split(X, y,test_size=0.33)



  (0, 7346)	1
  (0, 3226)	1
  (0, 9392)	1
  (0, 814)	1
  (0, 8301)	1
  (0, 3697)	1
  (0, 7155)	1
  (0, 8846)	1
  (0, 252)	1
  (0, 9683)	1
  (0, 4250)	1
  (0, 4980)	1
  (0, 5272)	1
  (0, 2141)	1
  (0, 5066)	1
  (0, 3213)	1
  (0, 2543)	3
  (0, 4135)	1
  (0, 5263)	1
  (0, 3644)	1
  (0, 8281)	1
  (0, 6803)	1
  (0, 4097)	1
  (0, 5121)	1
  (0, 1782)	1
  :	:
  (2836, 830)	1
  (2836, 4502)	1
  (2836, 2875)	1
  (2836, 4562)	1
  (2836, 4731)	1
  (2836, 4458)	1
  (2837, 7346)	2
  (2837, 2966)	1
  (2837, 5479)	2
  (2837, 8722)	1
  (2837, 8443)	1
  (2837, 6714)	1
  (2837, 4265)	1
  (2837, 9579)	1
  (2837, 5515)	1
  (2837, 8819)	1
  (2837, 5659)	1
  (2837, 2537)	1
  (2837, 7409)	1
  (2837, 2302)	1
  (2837, 7746)	1
  (2837, 2706)	1
  (2837, 8818)	1
  (2837, 5405)	1
  (2837, 2968)	1


In [26]:
from sklearn.naive_bayes import BernoulliNB
model=BernoulliNB()
model.fit(xtrain,ytrain)


BernoulliNB()

In [29]:
user=input("Enter the text")
data=cv.transform([user]).toarray()
output=model.predict(data)
print(output)

Enter the textuntil
[1]
